name:  PR checks
on: pull_request

env:
  SECRET_KEY: insecure_test_key

jobs:
  run-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: DOCKER_BUILDKIT=1 docker build --tag microk8s-io .
    - name: Run image
      run: |
        docker run -d -p 80:80 --env SECRET_KEY=insecure_secret_key microk8s-io
        sleep 1 && curl --head --fail --retry-delay 5 --retry 10 --retry-connrefused http://localhost

  lint-python:  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Install python dependencies
        run: sudo pip3 install flake8 black

      - name: Lint python
        run: yarn lint-python

  lint-scss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint scss
        run: yarn lint-scss

  test-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag microk8s-io .

      - name: Run tests
        run: docker run --env SECRET_KEY=insecure_secret_key --entrypoint python3 microk8s-io -m unittest discover tests
